apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-dashboard
spec:
  replicas: 2
  selector:
    matchLabels:
      app: student-dashboard
  template:
    metadata:
      labels:
        app: student-dashboard
    spec:
      containers:
        - name: student-dashboard
          image: your-dockerhub-username/student-dashboard:latest
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: student-dashboard-service
spec:
  type: NodePort
  selector:
    app: student-dashboard
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30007
