apiVersion: v1
kind: Service
metadata:
  name: student-dashboard-service
spec:
  selector:
    app: student-dashboard
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30007
